# Generated by Django 5.2.7 on 2025-10-03 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_remove_customuser_suspended_by'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='degree',
            options={'ordering': ['degree_type', 'name'], 'verbose_name': 'Degree Program', 'verbose_name_plural': 'Degree Programs'},
        ),
        migrations.AlterField(
            model_name='degree',
            name='degree_type',
            field=models.CharField(choices=[('S1', 'Senior One'), ('S2', 'Senior Two'), ('S3', 'Senior Three'), ('S4', "Senior Four (O'Level)"), ('S5', 'Senior Five'), ('S6', "Senior Six (A'Level)")], max_length=20),
        ),
    ]
