# Generated by Django 5.2.7 on 2025-10-12 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_company_address_company_created_by_company_email_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='graduationyear',
            options={'ordering': ['display_order', 'year'], 'verbose_name': 'Class Level', 'verbose_name_plural': 'Class Levels'},
        ),
        migrations.AddField(
            model_name='graduationyear',
            name='description',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='graduationyear',
            name='display_order',
            field=models.PositiveIntegerField(default=0, help_text='Controls the ordering of levels in lists'),
        ),
        migrations.AlterField(
            model_name='graduationyear',
            name='year',
            field=models.CharField(choices=[('S1', 'Senior One (S1)'), ('S2', 'Senior Two (S2)'), ('S3', 'Senior Three (S3)'), ('S4', "Senior Four (S4) - O' Level"), ('S5', 'Senior Five (S5)'), ('S6', "Senior Six (S6) - A' Level"), ('O_LEVEL', "Completed O' Level"), ('A_LEVEL', "Completed A' Level")], max_length=20, unique=True),
        ),
    ]
