# Generated by Django 5.2.7 on 2025-10-12 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_alter_graduationyear_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alumni',
            options={'ordering': ['graduation_year__display_order', 'admin__last_name'], 'verbose_name': 'Alumni', 'verbose_name_plural': 'Alumni'},
        ),
        migrations.AlterModelOptions(
            name='degree',
            options={'ordering': ['degree_type', 'name'], 'verbose_name': 'Level', 'verbose_name_plural': 'Levels'},
        ),
    ]
