# Generated by Django 5.2.7 on 2025-10-13 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_feedbackalumni_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagereply',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
