# Generated by Django 5.2.7 on 2025-10-14 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_alter_graduationyear_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='graduationyear',
            name='description',
        ),
    ]
